version: '2'
services:
  db2:
    image: postgres:9.6-alpine
    container_name: db2
    ports:
      - "5532:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres  
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8180:8080

volumes:
  postgres-data:
    driver: local
    